[scopes]
config = ["init.lua", "selene.toml", ".stylua.toml", ".neoconf.json", ".luarc.json", "lazy-lock.json", "lua/lazy_setup.lua", "lua/config", "lua/polish.lua", "lua/community.lua"]
plugins = ["lua/plugins"]
ci = [".github", "neovim.yml", "Dockerfile"]
docs = ["README.md"]
claude = ["claude/agents", "claude/commands", "claude/skills", "claude/.claude.json", "claude/settings.json"]
